spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pathwise
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000