spring:
  datasource:
    url: jdbc:h2:mem:pathwise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY}
  url: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.1-8b-instant
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}