spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pathwise
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY}
  url: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.1-8b-instant