spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY}
  url: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.1-8b-instant

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}